DROP TRIGGER IF EXISTS documents_au;
DROP TRIGGER IF EXISTS documents_ad;
DROP TRIGGER IF EXISTS documents_ai;
DROP TABLE IF EXISTS documents_fts;
DROP TRIGGER IF EXISTS cards_au;
DROP TRIGGER IF EXISTS cards_ad;
DROP TRIGGER IF EXISTS cards_ai;
DROP TABLE IF EXISTS cards_fts;
